language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
before_install:
  - npm install tape
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install lrzsz; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install lrzsz; fi
